config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'

  get '/about_me', to: 'static_pages#about_me', as: :about_me

  get '/contact', to: 'static_pages#contact', as: :contact

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	
	def show
		@post = Post.find(params[:id])
	end

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		if @post.save
		  redirect_to post_path(@post)
	    else
		  render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
		redirect_to post_path(@post)
	    else
	    	render :edit
	    end
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.destroy
			redirect_to posts_path
		else
			render :new
		end
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :author, :body)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def about_me
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  	<nav>
  	  <ul class="nav navbar-nav pull-right">
  		<li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Me", about_me_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "My Blog", posts_path %></li>
      </ul>
    </nav>
  </div>

</header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Me", about_me_path %></li> 
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "My Blog", posts_path %></li>  
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/navbar' %>
    <%= yield %>
    
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :author %>
  <%= f.text_field :author %>
</div>

<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

<div>
  <%= f.submit %>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to "Back", posts_path %>

app/views/posts/index.html.erb
<h1>My Blog</h1>
<% @posts.each do |post| %>
 <h1><%= post.title %></h1>
 <h2><%= post.author %></h2>
 <p><%= post.body %></p>
 <br />
 
 <%= link_to 'Show', post_path(post) %>
<% end %>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2><%= @post.author %></h2>
<p><%= @post.body %></p>

<%= link_to 'Back', posts_path %>
<%= link_to 'Edit Post', edit_post_path(@post) %>
<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure that you want to delete?' }%>

app/views/static_pages/about_me.html.erb
<h1>About Me</h1>
<p>
	<strong>Name:</strong> Nicholas M. Vo <br />
	<strong>Age:</strong> 32 <br />
	<strong>Occupation:</strong> Student/Musician <br />
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
	<strong>Email:</strong> MofT4Studio@gmail.com
</p>

app/views/static_pages/home.html.erb
  <h1>Welcome to My Home Page</h1>
    